name: CI

on:
  - push
  - pull_request

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        run: echo ::set-output name=NVMRC::$(cat .nvmrc)
        id: nvm
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{steps.nvm.outputs.NVMRC }}
      - name: Install dependencies
        run: yarn install
  qa:
    name: QA
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: QA
        run: yarn qa
  release:
    name: Release
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Release
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
        run: yarn release

