name: CI

on:
  - push
  - pull_request

jobs:
  qa:
    name: QA
    runs-on: ubuntu-latest
    steps:
      - name: Setup
        uses: ./../setup.yml
      - name: QA
        run: yarn qa
  release:
    name: Release
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Setup
        uses: ./../setup.yml
      - name: Release
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
        run: yarn release

