name: Release

on:
  push:
    branches:
      - master

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup node version
        run: echo ::set-output name=NODE_VERSION::$(cat .nvmrc)
        id: nvm
      - name: Setup node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{steps.nvm.outputs.NODE_VERSION }}
      - name: Install dependencies
        run: yarn install
      - name: QA
        run: yarn qa
      - name: Release
        run: yarn release
